### PR TITLE
MINOR: Cli script fix undefined variable file

### PR DESCRIPTION
**Pull request by shoaibali**
I am not sure if this is appropriate fix for this due to my limited knowledge of python. I suspect there use to be a file variable defined. The above is a quick fix for following error

NameError: name 'file' is not defined

### CODE REVIEW

**Comment by holloway** [comment]
Thanks! You're right that argparse in Python2 used an =file whereas Python3 does it a different way, so I fixed some other things while I was in there to do with binary vs unicode in Python3. Usage remains the same eg

$ cat doc/sample/sample-document.odt | python3 docvert-cli.py --autopipeline="Break up over Heading 1.default" --pipeline=basic

**Comment by shoaibali** [comment]
Excellent, thank you so much. I will make some more pull requests regarding improving the documentation regarding examples. I had to reverse engineer the web service to see what are acceptable pipelines and how to integrate them usin cURL. etc.

Secondly, I struggled with python-uno as that has been replaced in libreoffice. In relation to documentation again. 

:)

**Comment by holloway** [comment]
Sounds good. I'm on Mint 17.2 which has python3-uno but not python-uno

**Comment by shoaibali** [comment]
Yes, that one (python3-uno) is fine. Maybe I should log this issue on the docvert-python2. For some silly reason I have both python2 and python3 on my system (not sure how that happened). I wanted to try docvert-python2. So I got this message

```
sudo apt-get install python-uno
[sudo] password for shoaib:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-uno is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libreoffice-script-provider-python
```

**Pull request closed without merging**
